name: CI
on: [push]
jobs:
  eslint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkoutv2

      - name: Install packages
      - run: npm ci

      - name: Run eslint
      - run: npm run lint

      - name: Test code
      - run: npm run test
